// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDOIV1NxizBJZc9MdDPlK8E2H1_-9QZ0',
    appId: '1:256737748742:web:11caefd629b3a738556087',
    messagingSenderId: '256737748742',
    projectId: 'public-chat-app-2',
    authDomain: 'public-chat-app-2.firebaseapp.com',
    storageBucket: 'public-chat-app-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0oQKIQspz7Nsoy3vc528WDTnkMA32ow',
    appId: '1:256737748742:android:90165786a3ce1f7a556087',
    messagingSenderId: '256737748742',
    projectId: 'public-chat-app-2',
    storageBucket: 'public-chat-app-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15wNglPx6n0II2a9oMCeX_UIKQ_esssA',
    appId: '1:256737748742:ios:ad784a8010517985556087',
    messagingSenderId: '256737748742',
    projectId: 'public-chat-app-2',
    storageBucket: 'public-chat-app-2.firebasestorage.app',
    iosBundleId: 'com.rishikesh.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD15wNglPx6n0II2a9oMCeX_UIKQ_esssA',
    appId: '1:256737748742:ios:ad784a8010517985556087',
    messagingSenderId: '256737748742',
    projectId: 'public-chat-app-2',
    storageBucket: 'public-chat-app-2.firebasestorage.app',
    iosBundleId: 'com.rishikesh.chatapp.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnDOIV1NxizBJZc9MdDPlK8E2H1_-9QZ0',
    appId: '1:256737748742:web:5c7833f114535be0556087',
    messagingSenderId: '256737748742',
    projectId: 'public-chat-app-2',
    authDomain: 'public-chat-app-2.firebaseapp.com',
    storageBucket: 'public-chat-app-2.firebasestorage.app',
  );
}
